### ISSUE TITLE
Endless Log entry 

### ISSUE THREAD

**Issue by FreezeManny** [Clon1998/mobileraker_companion#22]
The mobileraker companion on my Mainsail install writes almost endless log entries.
I only noticed, once my 32 gb SD Card was filled with 24gb of logs saying the same thing:
![image](https://user-images.githubusercontent.com/55148495/224690117-25b11f1d-fbee-4c72-9c57-94369dff1322.png)
It keeps on entering this in my log.

**Comment by Clon1998** [comment]
Hey,
thats definitely not intended.
Can you stop the service, delete the log file. Start it again wait a few seconds, stop it again and attach the newly created log file?

**Comment by jangrewe** [comment]
I have the same issue, multiple times already. Not sure what causes it, but restarting Mobileraker "fixes" it ... until the next time this happens. ;-)

**Comment by Clon1998** [comment]
Should be fixed with [8c2df47](https://github.com/Clon1998/mobileraker_companion/commit/8c2df4760d147287b5ebf0a3e9159777e89104e3)

**Comment by jangrewe** [comment]
Thanks, a quick test with restarting Klipper and adjacent services confirms that this is indeed fixed! 🥳

**Comment by FreezeManny** [comment]
On my end it is not fixed. It does the exact same thing as before on a fresh install.

**Comment by Clon1998** [comment]
> On my end it is not fixed. It does the exact same thing as before on a fresh install.

Alright, can you stop the service and send the first few log entries ?
